version: "3.4"

services:
  watch:
    image: watch
    build:
      dockerfile: ./docker/watch/Dockerfile
      target: vue
      context: .
    volumes:
      - ./watch:/app:ro
      # Exclude node_modules/ from host.
      - /app/node_modules/
      - ./docker/watch/entrypoint.sh:/entrypoint.sh:ro
    ports:
      - 8002:8002
