name: Build Docker
run-name: Creating Docker Image 🚀
on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    name: Build docker
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: install docker
        uses: docker-practice/actions-setup-docker@master

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build app
        run: |
          npm i
          make build

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: build and push watch
        run: |
          docker build -f docker/watch/Dockerfile \
            --tag ${{ secrets.DOCKER_ORG }}/watch:latest \
            --tag ${{ secrets.DOCKER_ORG }}/watch:${{ steps.package-version.outputs.current-version }} \
            .
          docker push ${{ secrets.DOCKER_ORG }}/watch:latest
          docker push ${{ secrets.DOCKER_ORG }}/watch:${{ steps.package-version.outputs.current-version }}
