name: Build Electrion
run-name: Creating Production Ready Electron App 🚀
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Electron
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Install wine
        run: sudo apt install -y wine64

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: install dependencies
        run: npm ci

      - name: install electron
        run: |
          pushd electron
          npm i
          popd

      - name: build app
        run: make package-electron
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Check folder content of electron output
        run: ls ./electron/dist
